baseURL = 'https://www.lillystone.co.uk/'
languageCode = 'en-us'
title = ''
theme = "PaperMod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.homeInfoParams]
  Title = "James Lillystone"
  Content = """
Cloud & Security Architect · Azure · DevSecOps · Compliance & Governance

📧 [james@lillystone.co.uk](mailto:james@lillystone.co.uk)  
💻 [GitHub](https://github.com/BarryShtPeas)  
🔗 [LinkedIn](https://www.linkedin.com/in/jameslillystone/)
"""